# Generated by Django 5.0.7 on 2024-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
                ('pdetails', models.CharField(max_length=100, verbose_name='Product Details')),
                ('pcategory', models.IntegerField(choices=[(1, 'Shoes'), (2, 'T-Shirts'), (3, 'Shorts')], verbose_name='Category')),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Available')),
            ],
        ),
    ]
