# Generated by Django 5.0.7 on 2024-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_productdata_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='pimage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
